parameters:
    tks.services.class: Tks\TksBundle\Controller\ServicesController

services:
    db.service:
        class: %tks.services.class%
        arguments: [ @doctrine.orm.entity_manager ]
#        arguments: [@service_id, "plain_value", %parameter%]
