Tks\TksBundle\Entity\Languages:
    type: entity
    table: languages
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        name:
            type: string
            length: 25
            fixed: false
            nullable: false
    lifecycleCallbacks: {  }
